logging:
  level:
    se:
      sundsvall:
        dept44:
          payload: OFF

spring:
  main:
    banner-mode: off
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    # Inserting large templates so we need to increase the max_allowed_packet in MariaDB 
    # using configuration file (db/mariadb.cnf) and then point to the directory where it's placed
    # Not the file, that doesn't work.
    url: jdbc:tc:mariadb:10.6:///?TC_MY_CNF=db
