version: '3'
services:
  templating:
    container_name: ms-templating-sandbox
    image: 'ms-templating:latest'
    restart: always
    depends_on:
      - ms-templating-sandbox-wiremock
    links:
      - ms-templating-sandbox-wiremock:wiremock
    ports:
      - '9061:8080'
    environment:
      - JAVA_OPTS=-server -Dfile.encoding=UTF-8 -Xms128m -Xmx256m
      - SPRING_PROFILES_ACTIVE=sandbox
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:sandbox
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=false

  ms-templating-sandbox-wiremock:
    container_name: ms-templating-sandbox-wiremock
    image: wiremock/wiremock:2.32.0
    restart: always
    expose:
      - '8080'
    volumes:
      - $PWD/src/sandbox/wiremock:/home/wiremock

